/**
 * useCreatePayment — TanStack Query mutation for starting a MercadoPago Checkout Pro flow.
 *
 * Change 19 — payments-mercadopago-integration (Checkout Pro migration).
 *
 * Calls POST /api/v1/pagos with { pedido_id, idempotency_key }.
 * On success: updates paymentStore to status="pending" (preference created, awaiting payment).
 * On error: updates paymentStore to status="error" and stores the error code.
 *
 * Design decisions:
 * - Checkout Pro: no card token — idempotency_key is generated by caller.
 * - The store status="pending" means "preference created, waiting for MP webhook".
 *   The actual approval is signaled by the IPN webhook, not by this mutation response.
 * - PayWithMercadoPagoButton uses this hook internally or directly calls createPayment.
 */

import { useMutation } from '@tanstack/react-query'
import { usePaymentStore } from '@/shared/store/paymentStore'
import { createPayment } from '@/entities/pago'
import type { PagoCreateRequest, PagoResponse } from '@/entities/pago'

/**
 * Arguments passed to mutateAsync().
 * Matches PagoCreateRequest — pedido_id from store, idempotency_key from caller.
 */
export interface CreatePaymentArgs {
  idempotency_key: string
}

/**
 * Hook for starting a MercadoPago Checkout Pro payment.
 *
 * @returns TanStack Query mutation object:
 *   - mutateAsync: trigger with CreatePaymentArgs (idempotency_key)
 *   - isPending: true while request is in-flight
 *   - isError: true if preference creation failed
 *   - data: PagoResponse with init_point on success
 *   - error: AxiosError on failure
 */
export function useCreatePayment() {
  const pedidoId = usePaymentStore((state) => state.pedidoId)
  const setStatus = usePaymentStore((state) => state.setStatus)
  const setLastErrorCode = usePaymentStore((state) => state.setLastErrorCode)

  const mutation = useMutation<PagoResponse, Error, CreatePaymentArgs>({
    mutationFn: async (args: CreatePaymentArgs) => {
      if (!pedidoId) {
        throw new Error('No pedidoId in paymentStore — call startCheckout first.')
      }

      const request: PagoCreateRequest = {
        pedido_id: pedidoId,
        idempotency_key: args.idempotency_key,
      }

      return createPayment(request)
    },
    onSuccess: () => {
      // Preference created — waiting for user to pay on MP hosted page.
      // After redirect + payment, webhook will fire and polling will detect it.
      setStatus('pending')
      setLastErrorCode(null)
    },
    onError: (error) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const axiosError = error as any
      const code = axiosError?.response?.data?.code as string | undefined
      setStatus('error')
      setLastErrorCode(code ?? 'MP_PREFERENCE_ERROR')
    },
  })

  return {
    mutateAsync: mutation.mutateAsync,
    isPending: mutation.isPending,
    isError: mutation.isError,
    isSuccess: mutation.isSuccess,
    data: mutation.data,
    error: mutation.error,
  }
}
