"""0001_initial_schema

Revision ID: 6ebe5e787bdd
Revises: 
Create Date: 2026-05-12 12:18:50.754649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — AutoString types referenced in autogenerated migration


# revision identifiers, used by Alembic.
revision: str = '6ebe5e787bdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categoria.id'], name=op.f('fk_categoria_parent_id_categoria'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria')),
    sa.UniqueConstraint('nombre', name=op.f('uq_categoria_nombre'))
    )
    op.create_table('estado_pedido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('es_terminal', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estado_pedido')),
    sa.UniqueConstraint('codigo', name=op.f('uq_estado_pedido_codigo'))
    )
    op.create_table('forma_pago',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forma_pago')),
    sa.UniqueConstraint('codigo', name=op.f('uq_forma_pago_codigo'))
    )
    op.create_table('ingrediente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('es_alergeno', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingrediente')),
    sa.UniqueConstraint('nombre', name=op.f('uq_ingrediente_nombre'))
    )
    op.create_table('producto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('precio_base', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock_cantidad', sa.Integer(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.CheckConstraint('precio_base >= 0', name=op.f('ck_producto_precio_base')),
    sa.CheckConstraint('stock_cantidad >= 0', name=op.f('ck_producto_stock_cantidad')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producto'))
    )
    op.create_table('rol',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rol')),
    sa.UniqueConstraint('codigo', name=op.f('uq_rol_codigo'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('password_hash', sa.CHAR(length=60), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email'))
    )
    op.create_table('direccion_entrega',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('linea1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linea2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_direccion_entrega_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_direccion_entrega'))
    )
    op.create_table('producto_categoria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_producto_categoria_categoria_id_categoria'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('fk_producto_categoria_producto_id_producto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producto_categoria')),
    sa.UniqueConstraint('producto_id', 'categoria_id', name='uq_producto_categoria_producto_id_categoria_id')
    )
    op.create_table('producto_ingrediente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('ingrediente_id', sa.Uuid(), nullable=False),
    sa.Column('es_removible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingrediente.id'], name=op.f('fk_producto_ingrediente_ingrediente_id_ingrediente'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('fk_producto_ingrediente_producto_id_producto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producto_ingrediente')),
    sa.UniqueConstraint('producto_id', 'ingrediente_id', name='uq_producto_ingrediente_producto_id_ingrediente_id')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_refresh_token_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_token_token_hash'))
    )
    op.create_index(op.f('ix_refresh_token_usuario_id'), 'refresh_token', ['usuario_id'], unique=False)
    op.create_table('usuario_rol',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('asignado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por_id'], ['usuario.id'], name=op.f('fk_usuario_rol_asignado_por_id_usuario')),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name=op.f('fk_usuario_rol_rol_id_rol'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_usuario_rol_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario_rol')),
    sa.UniqueConstraint('usuario_id', 'rol_id', name='uq_usuario_rol_usuario_id_rol_id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('estado_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('forma_pago_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('direccion_id', sa.Uuid(), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('costo_envio', sa.DECIMAL(precision=10, scale=2), server_default='50.00', nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('costo_envio >= 0', name=op.f('ck_pedido_costo_envio')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_pedido_total')),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccion_entrega.id'], name=op.f('fk_pedido_direccion_id_direccion_entrega'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estado_pedido.codigo'], name=op.f('fk_pedido_estado_codigo_estado_pedido')),
    sa.ForeignKeyConstraint(['forma_pago_codigo'], ['forma_pago.codigo'], name=op.f('fk_pedido_forma_pago_codigo_forma_pago')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_pedido_usuario_id_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedido'))
    )
    op.create_index(op.f('ix_pedido_estado_codigo'), 'pedido', ['estado_codigo'], unique=False)
    op.create_index(op.f('ix_pedido_usuario_id'), 'pedido', ['usuario_id'], unique=False)
    op.create_table('detalle_pedido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_snapshot', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('precio_snapshot', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('personalizacion', sa.ARRAY(sa.Integer()), nullable=True),
    sa.CheckConstraint('cantidad >= 1', name=op.f('ck_detalle_pedido_cantidad')),
    sa.CheckConstraint('precio_snapshot >= 0', name=op.f('ck_detalle_pedido_precio_snapshot')),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], name=op.f('fk_detalle_pedido_pedido_id_pedido'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('fk_detalle_pedido_producto_id_producto'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_pedido'))
    )
    op.create_index(op.f('ix_detalle_pedido_pedido_id'), 'detalle_pedido', ['pedido_id'], unique=False)
    op.create_table('historial_estado_pedido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('estado_desde', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('estado_hasta', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cambiado_por_id', sa.Uuid(), nullable=True),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['cambiado_por_id'], ['usuario.id'], name=op.f('fk_historial_estado_pedido_cambiado_por_id_usuario')),
    sa.ForeignKeyConstraint(['estado_desde'], ['estado_pedido.codigo'], name=op.f('fk_historial_estado_pedido_estado_desde_estado_pedido')),
    sa.ForeignKeyConstraint(['estado_hasta'], ['estado_pedido.codigo'], name=op.f('fk_historial_estado_pedido_estado_hasta_estado_pedido')),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], name=op.f('fk_historial_estado_pedido_pedido_id_pedido'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historial_estado_pedido'))
    )
    op.create_index(op.f('ix_historial_estado_pedido_pedido_id'), 'historial_estado_pedido', ['pedido_id'], unique=False)
    op.create_table('pago',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('mp_payment_id', sa.BIGINT(), nullable=True),
    sa.Column('mp_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('external_reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], name=op.f('fk_pago_pedido_id_pedido'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pago')),
    sa.UniqueConstraint('external_reference', name=op.f('uq_pago_external_reference')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_pago_idempotency_key')),
    sa.UniqueConstraint('mp_payment_id', name=op.f('uq_pago_mp_payment_id'))
    )
    op.create_index(op.f('ix_pago_pedido_id'), 'pago', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pago_pedido_id'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_historial_estado_pedido_pedido_id'), table_name='historial_estado_pedido')
    op.drop_table('historial_estado_pedido')
    op.drop_index(op.f('ix_detalle_pedido_pedido_id'), table_name='detalle_pedido')
    op.drop_table('detalle_pedido')
    op.drop_index(op.f('ix_pedido_usuario_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_estado_codigo'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_table('usuario_rol')
    op.drop_index(op.f('ix_refresh_token_usuario_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_table('producto_ingrediente')
    op.drop_table('producto_categoria')
    op.drop_table('direccion_entrega')
    op.drop_table('usuario')
    op.drop_table('rol')
    op.drop_table('producto')
    op.drop_table('ingrediente')
    op.drop_table('forma_pago')
    op.drop_table('estado_pedido')
    op.drop_table('categoria')
    # ### end Alembic commands ###
